INSERT INTO ingredients (id, name, category, subcategory, unit, vendor, vendor_code, pack_size, case_price, brand, programs, storage, is_active, hidden_from_instructor) VALUES
('SYS2456846', 'Milk, Whole Homogenized', 'Dairy & Eggs', 'Milk', 'gal', 'Sysco', '2456846', '6/.5GAL', 19.59, 'Wholesome Farms', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS2491702', 'Buttermilk, 1% Low Fat', 'Dairy & Eggs', 'Milk', 'gal', 'Sysco', '2491702', '6/.5GAL', 15.99, 'Wholesome Farms', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS4828802', 'Cream, Heavy Whipping 36%', 'Dairy & Eggs', 'Cream', 'oz', 'Sysco', '4828802', '12/32OZ', 48.29, 'Wholesome Farms', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS0284861', 'Sour Cream', 'Dairy & Eggs', 'Cream', 'lb', 'Sysco', '0284861', '2/5LB', 19.45, 'Wholesome Farms', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS7485170', 'Butter, Unsalted AA', 'Dairy & Eggs', 'Butter', 'lb', 'Sysco', '7485170', '30/1LB', 84.34, 'Wholesome Farms Imperial', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS3029475', 'Butter Chips, Salted Continental', 'Dairy & Eggs', 'Butter', 'lb', 'Sysco', '3029475', '4/4.25LB', 69.69, 'Wholesome Farms Imperial', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS2105823', 'Eggs, Large Grade AA White', 'Dairy & Eggs', 'Eggs', 'ea', 'Sysco', '2105823', '1/15DZ', 34.89, 'Wholesome Farms', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS5134365', 'Eggs, Scramble Mix Liquid', 'Dairy & Eggs', 'Eggs', 'lb', 'Sysco', '5134365', '15/2LB', 87.99, 'Wholesome Farms Imperial', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS2822353', 'Cheese, Cheddar Sharp Shredded', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '2822353', '4/5LB', 54.67, 'Block & Barrel', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS0873301', 'Cheese, Parmesan Shredded', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '0873301', '4/5LB', 102.99, 'Arrezzio', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS2329437', 'Cheese, Mozzarella Shredded WM', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '2329437', '4/5LB', 52.27, 'Arrezzio Imperial', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS3716750', 'Cheese, Cream Loaf', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '3716750', '6/3LB', 83.49, 'Philadelphia', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS3717279', 'Cheese, Cream Cups 1oz', 'Dairy & Eggs', 'Cheese', 'ea', 'Sysco', '3717279', '100/1OZ', 47.65, 'Philadelphia', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS1037316', 'Yogurt, Plain Low Fat', 'Dairy & Eggs', 'Yogurt', 'oz', 'Sysco', '1037316', '6/32OZ', 30.95, 'Dannon', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B001', 'Flour, All Purpose', 'Pantry', 'Flours', 'lb', 'Sysco', '8379251', '1/25LB', 10.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B002', 'Flour, Cake', 'Pantry', 'Flours', 'lb', 'Sysco', '4014494', '1/50LB', 27.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B003', 'Flour, Bread', 'Pantry', 'Flours', 'lb', 'Sysco', '5035217', '1/50LB', 18.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B004', 'Flour, Pastry', 'Pantry', 'Flours', 'lb', 'Sysco', '4567186', '1/50LB', 28.79, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B005', 'Flour, Whole Wheat', 'Pantry', 'Flours', 'lb', 'Sysco', '4014684', '1/50LB', 18.75, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B006', 'Flour, Rye', 'Pantry', 'Flours', 'lb', 'Sysco', '5765724', '1/50LB', 47.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B007', 'Flour, Semolina', 'Pantry', 'Flours', 'lb', 'Sysco', '5765732', '1/50LB', 55.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B008', 'Cornmeal', 'Pantry', 'Grains', 'lb', 'Sysco', '5765740', '1/50LB', 32.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B009', 'Polenta', 'Pantry', 'Grains', 'lb', 'Sysco', '4147923', '6/5LB', 42.9, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B010', 'Flour, Masa Harina', 'Pantry', 'Flours', 'lb', 'Sysco', '5792163', '8/4.4LB', 41.79, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B011', 'Flour, Mesquite', 'Pantry', 'Flours', 'lb', 'Sysco', '5765756', '1/5LB', 42.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B012', 'Oats, Rolled', 'Pantry', 'Grains', 'lb', 'Sysco', '4082666', '1/25LB', 26.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B013', 'Quinoa', 'Pantry', 'Grains', 'lb', 'Sysco', '2404410', '1/25LB', 137.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B020', 'Sugar, Granulated', 'Pantry', 'Sweeteners', 'lb', 'Sysco', '4082682', '1/50LB', 39.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B021', 'Sugar, Powdered', 'Pantry', 'Sweeteners', 'lb', 'Sysco', '5593900', '12/2LB', 37.59, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B022', 'Sugar, Brown Light', 'Pantry', 'Sweeteners', 'lb', 'Sysco', '4082690', '1/50LB', 46.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B023', 'Sugar, Brown Dark', 'Pantry', 'Sweeteners', 'lb', 'Sysco', '4082698', '1/50LB', 47.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B024', 'Honey', 'Pantry', 'Sweeteners', 'oz', 'Sysco', '5611652', '6/5LB', 130.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B025', 'Syrup, Maple', 'Pantry', 'Sweeteners', 'oz', 'Sysco', '4082730', '4/1GAL', 435.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B026', 'Molasses', 'Pantry', 'Sweeteners', 'oz', 'Sysco', '4082722', '4/1GAL', 102.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B027', 'Syrup, Corn Light', 'Pantry', 'Sweeteners', 'oz', 'Sysco', '5296504', '4/1GAL', 81.85, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B028', 'Syrup, Corn Dark', 'Pantry', 'Sweeteners', 'oz', 'Sysco', '4005294', '4/1GAL', 78.45, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B031', 'Eggs, Large', 'Dairy & Eggs', 'Eggs', 'doz', 'Sysco', '6200887', '1/15DOZ', 43.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B032', 'Milk, Whole', 'Dairy & Eggs', 'Milk & Cream', 'gal', 'Sysco', '2327740', '4/1GAL', 26.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B035', 'Cream, Sour', 'Dairy & Eggs', 'Cultured Dairy', 'lb', 'Sysco', '5020193', '2/5LB', 19.79, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B036', 'Cheese, Cream', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '1012566', '10/3LB', 82.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B037', 'Mascarpone', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '2389153', '12/16OZ', 58.65, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B038', 'Yogurt, Plain', 'Dairy & Eggs', 'Cultured Dairy', 'lb', 'Sysco', '8133573', '1/32LB', 57.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B039', 'Half & Half', 'Dairy & Eggs', 'Milk & Cream', 'qt', 'Sysco', '4828844', '12/1QT', 17.16, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B040', 'Chocolate, Chips', 'Pantry', 'Chocolate & Cocoa', 'lb', 'Sysco', '5335732', '1/25LB', 148.79, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B041', 'Chocolate, Dark Callets', 'Pantry', 'Chocolate & Cocoa', 'lb', 'Sysco', '5190505', '1/10KG', 322.85, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B042', 'Chocolate, Milk Callets', 'Pantry', 'Chocolate & Cocoa', 'lb', 'Sysco', '7046854', '1/10KG', 321.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B043', 'Chocolate, White Callets', 'Pantry', 'Chocolate & Cocoa', 'lb', 'Sysco', '7322530', '1/10KG', 373.69, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B044', 'Cocoa, Natural', 'Pantry', 'Chocolate & Cocoa', 'lb', 'Sysco', '7286241', '1/2.2LB', 38.59, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B050', 'Almonds, Sliced', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '5963848', '3/2LB', 79.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B051', 'Almonds, Whole', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4645412', '3/2LB', 67.79, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B052', 'Pecans, Halves', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '7078389', '1/5LB', 80.89, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B053', 'Pecans, Pieces', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4645396', '3/2LB', 90.89, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B054', 'Walnuts, Halves', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4645388', '3/2LB', 65.55, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B056', 'Hazelnuts', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4082632', '1/25LB', 300.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B057', 'Pistachios', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '5529318', '1/5LB', 82.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B058', 'Cashews', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '7010545', '6/5LB', 228.45, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B059', 'Coconut, Shredded', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4504908', '1/10LB', 53.85, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B060', 'Extract, Vanilla', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '5230057', '6/32OZ', 69.59, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B061', 'Vanilla Beans', 'Pantry', 'Extracts & Flavorings', 'ea', 'Sysco', '9093196', '1/8OZ', 59.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B062', 'Extract, Almond', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '4082762', '1/32OZ', 40.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B063', 'Extract, Lemon', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '4082770', '1/32OZ', 35.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B070', 'Baking Powder', 'Pantry', 'Leaveners', 'lb', 'Sysco', '4082856', '1/5LB', 9.85, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B071', 'Baking Soda', 'Pantry', 'Leaveners', 'lb', 'Sysco', '4082864', '1/12LB', 18.48, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B072', 'Yeast, Active Dry', 'Pantry', 'Leaveners', 'lb', 'Sysco', '4082831', '1/2LB', 9.6, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B073', 'Yeast, Instant', 'Pantry', 'Leaveners', 'lb', 'Sysco', '4082839', '1/2LB', 10.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B074', 'Cream of Tartar', 'Pantry', 'Baking Ingredients', 'oz', 'Sysco', '7577028', '1/28OZ', 64.12, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B075', 'Gelatin, Sheet', 'Pantry', 'Thickeners', 'ea', 'Sysco', '8034894', '1/2.2LB', 59.55, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B076', 'Gelatin, Granules', 'Pantry', 'Thickeners', 'oz', 'Sysco', '4157257', '12/1LB', 263.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B080', 'Almond Paste', 'Pantry', 'Baking Ingredients', 'lb', 'Sysco', '4082738', '1/7LB', 66.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B081', 'Marzipan', 'Pantry', 'Baking Ingredients', 'lb', 'Sysco', '4082746', '1/7LB', 57.75, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B082', 'Sourdough Starter', 'Bakery & Bread', 'Other', 'oz', 'Sysco', '0000001', '1/16OZ', 40.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B090', 'Dough, Phyllo', 'Frozen Foods', 'Frozen Breads', 'lb', 'Sysco', '9451600', '24/16OZ', 130.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B091', 'Dough, Puff Pastry', 'Frozen Foods', 'Frozen Breads', 'sheet', 'Sysco', '7198009', '20/12OZ', 62.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B095', 'Raisins', 'Pantry', 'Dried Fruits', 'lb', 'Sysco', '4082526', '1/30LB', 84.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B096', 'Cherries, Dried', 'Pantry', 'Dried Fruits', 'lb', 'Sysco', '4082518', '1/5LB', 60.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B097', 'Apricots, Dried', 'Pantry', 'Dried Fruits', 'lb', 'Sysco', '4082500', '1/5LB', 32.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B098', 'Jam, Raspberry', 'Pantry', 'Jams & Preserves', 'lb', 'Sysco', '4082950', '6/4LB', 84.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B099', 'Jam, Apricot', 'Pantry', 'Jams & Preserves', 'lb', 'Sysco', '4082958', '6/4LB', 78.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B100', 'Peanut Butter', 'Pantry', 'Nut Butters', 'lb', 'Sysco', '3318498', '12/18OZ', 47.59, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B101', 'Tahini', 'Pantry', 'Condiments', 'lb', 'Sysco', '7190481', '6/2LB', 100.44, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B102', 'Extract, Coffee', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B103', 'Espresso Powder', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 24.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B104', 'Tea, Earl Grey', 'Beverages', 'Tea', 'oz', 'Sysco', '', '6/25CT', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B105', 'Tea, Green Matcha', 'Beverages', 'Tea', 'oz', 'Sysco', '', '1/100G', 45.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B106', 'Tea, Chamomile', 'Beverages', 'Tea', 'oz', 'Sysco', '', '6/25CT', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B107', 'Coffee, Ground', 'Beverages', 'Coffee', 'lb', 'Sysco', '', '6/2LB', 68.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B108', 'Coffee, Whole Bean', 'Beverages', 'Coffee', 'lb', 'Sysco', '', '6/2LB', 72.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B109', 'Extract, Orange', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 22.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B110', 'Extract, Peppermint', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 18.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B111', 'Extract, Coconut', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 16.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B112', 'Extract, Rum', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/16OZ', 14.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B113', 'Rose Water', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '12/10OZ', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B114', 'Orange Blossom Water', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '12/10OZ', 36.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B115', 'Lemon Zest, Dried', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/8OZ', 12.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B116', 'Orange Zest, Dried', 'Pantry', 'Extracts & Flavorings', 'oz', 'Sysco', '', '1/8OZ', 12.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B117', 'Candied Orange Peel', 'Pantry', 'Baking Ingredients', 'lb', 'Sysco', '', '1/5LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B118', 'Candied Lemon Peel', 'Pantry', 'Baking Ingredients', 'lb', 'Sysco', '', '1/5LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B120', 'Liqueur, Grand Marnier', 'Wine & Spirits', 'Liqueurs', 'oz', 'Sysco', '', '12/750ML', 320.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B121', 'Liqueur, Kahlua', 'Wine & Spirits', 'Liqueurs', 'oz', 'Sysco', '', '12/750ML', 280.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B122', 'Liqueur, Amaretto', 'Wine & Spirits', 'Liqueurs', 'oz', 'Sysco', '', '12/750ML', 240.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B123', 'Liqueur, Frangelico', 'Wine & Spirits', 'Liqueurs', 'oz', 'Sysco', '', '12/750ML', 260.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B124', 'Brandy, Cooking', 'Wine & Spirits', 'Spirits', 'oz', 'Sysco', '', '12/750ML', 180.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('B125', 'Rum, Dark', 'Wine & Spirits', 'Spirits', 'oz', 'Sysco', '', '12/750ML', 160.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S001', 'Orange, Fancy Fresh', 'Produce', 'Fruit', 'ea', 'Sysco', '7651973', '1/138CT', 31.29, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S002', 'Lemon', 'Produce', 'Fruit', 'ea', 'Sysco', '2538346', '1/140CT', 32.59, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S003', 'Lime', 'Produce', 'Fruit', 'ea', 'Sysco', '1185040', '1/175CT', 28.37, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S004', 'Apple, Green', 'Produce', 'Fruit', 'ea', 'Sysco', '5126867', '1/163CT', 32.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S005', 'Apple, Red', 'Produce', 'Fruit', 'lb', 'Sysco', '4473056', '1/40LB', 33.65, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S006', 'Banana', 'Produce', 'Fruit', 'lb', 'Sysco', '6894737', '1/5LB', 8.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S007', 'Strawberries', 'Produce', 'Fruit', 'pt', 'Sysco', '1681958', '4/1LB', 27.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S008', 'Blueberries', 'Produce', 'Fruit', 'pt', 'Sysco', '8864191', '6/.5PT', 31.69, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S009', 'Raspberries', 'Produce', 'Fruit', 'pt', 'Sysco', '6196810', '6/.5PT', 28.99, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S010', 'Blackberries', 'Produce', 'Fruit', 'pt', 'Sysco', '2017986', '6/.5PT', 26.45, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S020', 'Onion, Yellow', 'Produce', 'Vegetables', 'lb', 'Sysco', '1094721', '1/50LB', 33.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S021', 'Onion, Red', 'Produce', 'Vegetables', 'lb', 'Sysco', '1094739', '1/25LB', 21.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S022', 'Onion, Green', 'Produce', 'Vegetables', 'bunch', 'Sysco', '3456887', '48CT', 31.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S023', 'Shallots', 'Produce', 'Vegetables', 'lb', 'Sysco', '0077180', '1/5LB', 16.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S024', 'Garlic', 'Produce', 'Vegetables', 'ea', 'Sysco', '0077172', '30CT', 13.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S025', 'Leeks', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456821', '12CT', 22.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S026', 'Carrot', 'Produce', 'Vegetables', 'lb', 'Sysco', '3456805', '1/50LB', 29.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S027', 'Celery', 'Produce', 'Vegetables', 'bunch', 'Sysco', '3456813', '24CT', 36.72, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S028', 'Potato, Russet', 'Produce', 'Vegetables', 'lb', 'Sysco', '1008432', '1/50LB', 29.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S029', 'Potato, Red', 'Produce', 'Vegetables', 'lb', 'Sysco', '1008440', '1/50LB', 36.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S030', 'Asparagus', 'Produce', 'Vegetables', 'lb', 'Sysco', '3460557', '1/11LB', 48.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S031', 'Bell Pepper, Green', 'Produce', 'Vegetables', 'ea', 'Sysco', '4615712', '25CT', 21.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S032', 'Bell Pepper, Red', 'Produce', 'Vegetables', 'ea', 'Sysco', '4615704', '25CT', 31.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S033', 'Jalapeno', 'Produce', 'Vegetables', 'lb', 'Sysco', '4615720', '1/10LB', 18.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S034', 'Tomato, Roma', 'Produce', 'Vegetables', 'lb', 'Sysco', '5418132', '1/25LB', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S035', 'Tomato, Cherry', 'Produce', 'Vegetables', 'pt', 'Sysco', '5418140', '12PT', 30.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S036', 'Cucumber', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456895', '24CT', 13.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S037', 'Cucumber, English', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456903', '12CT', 15.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S038', 'Zucchini', 'Produce', 'Vegetables', 'lb', 'Sysco', '3456929', '1/20LB', 27.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S039', 'Squash, Yellow', 'Produce', 'Vegetables', 'lb', 'Sysco', '3456911', '1/20LB', 29.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S040', 'Eggplant', 'Produce', 'Vegetables', 'lb', 'Sysco', '1222389', '1/20LB', 33.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S041', 'Mushrooms, Cremini', 'Produce', 'Vegetables', 'lb', 'Sysco', '4754909', '1/10LB', 36.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S042', 'Corn, Fresh', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456837', '48CT', 31.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S043', 'Spinach', 'Produce', 'Vegetables', 'lb', 'Sysco', '3456861', '4/2.5LB', 28.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S044', 'Lettuce, Romaine', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456845', '24CT', 30.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S045', 'Lettuce, Iceberg', 'Produce', 'Vegetables', 'ea', 'Sysco', '3456853', '24CT', 26.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S046', 'Lettuce, Spring Mix', 'Produce', 'Vegetables', 'lb', 'Sysco', '3456879', '4/3LB', 54.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S047', 'Avocado', 'Produce', 'Vegetables', 'ea', 'Sysco', '9230970', '48CT', 36.96, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S060', 'Basil, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '2004521', '1LB', 15.04, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S061', 'Cilantro', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004919', '30CT', 19.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S062', 'Parsley, Flat Leaf', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004935', '30CT', 25.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S063', 'Parsley, Curly', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004927', '30CT', 22.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S064', 'Mint, Fresh', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004893', '12CT', 15.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S065', 'Thyme, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '2005270', '1LB', 17.92, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S066', 'Rosemary, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '2005288', '1LB', 15.2, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S067', 'Sage, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '2004943', '1LB', 13.44, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S068', 'Dill, Fresh', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004901', '12CT', 11.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S069', 'Chives, Fresh', 'Produce', 'Fresh Herbs', 'bunch', 'Sysco', '2004885', '12CT', 17.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S080', 'Chicken, Breast', 'Meat & Seafood', 'Poultry', 'lb', 'Sysco', '1860303', '40LB', 154.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S081', 'Chicken, Whole', 'Meat & Seafood', 'Poultry', 'lb', 'Sysco', '1860295', '4/4LB', 26.56, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S082', 'Beef, Ground 80/20', 'Meat & Seafood', 'Beef', 'lb', 'Sysco', '1860311', '10LB', 42.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S083', 'Beef, Strip Loin', 'Meat & Seafood', 'Beef', 'lb', 'Sysco', '1860329', '1/15LB', 187.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S084', 'Pork, Loin', 'Meat & Seafood', 'Pork', 'lb', 'Sysco', '1860337', '1/10LB', 48.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S085', 'Bacon', 'Meat & Seafood', 'Pork', 'lb', 'Sysco', '1860345', '15LB', 97.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S086', 'Sausage, Italian', 'Meat & Seafood', 'Pork', 'lb', 'Sysco', '2434371', '10LB', 39.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S087', 'Salmon, Fillet', 'Meat & Seafood', 'Seafood', 'lb', 'Sysco', '9907462', '10LB', 111.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S088', 'Shrimp, 16/20', 'Meat & Seafood', 'Seafood', 'lb', 'Sysco', '9907470', '10LB', 98.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S090', 'Cheese, Cheddar', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '7234958', '10LB', 47.3, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S091', 'Cheese, Parmesan Shredded', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '4067033', '4/5LB', 114.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S100', 'Stock, Chicken', 'Stock', 'Chicken Stock', 'qt', 'Sysco', '4082200', '12/1QT', 30.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S101', 'Stock, Beef', 'Stock', 'Beef Stock', 'qt', 'Sysco', '4082208', '12/1QT', 33.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S102', 'Stock, Vegetable', 'Stock', 'Vegetable Stock', 'qt', 'Sysco', '4082216', '12/1QT', 27.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S110', 'Oil, Olive', 'Pantry', 'Oils & Vinegars', 'gal', 'Sysco', '4082100', '6/1GAL', 135.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S111', 'Oil, Canola', 'Pantry', 'Oils & Vinegars', 'gal', 'Sysco', '4082794', '6/1GAL', 55.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S112', 'Oil, Vegetable', 'Pantry', 'Oils & Vinegars', 'gal', 'Sysco', '4082786', '6/1GAL', 51.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S113', 'Shortening, Vegetable', 'Pantry', 'Oils & Vinegars', 'lb', 'Sysco', '4082778', '50LB', 69.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S114', 'Vinegar, Balsamic', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '4082116', '2/1GAL', 89.6, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S115', 'Vinegar, Red Wine', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '4082124', '4/1GAL', 76.8, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S116', 'Vinegar, White Wine', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '4082132', '4/1GAL', 61.44, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S120', 'Salt, Kosher', 'Pantry', 'Spices & Seasonings', 'lb', 'Sysco', '4082872', '3LB', 3.24, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S121', 'Salt, Table', 'Pantry', 'Spices & Seasonings', 'lb', 'Sysco', '4082880', '25LB', 11.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S123', 'Paprika', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082516', '16OZ', 5.6, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S124', 'Cumin, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082524', '16OZ', 6.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S125', 'Oregano, Dried', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082532', '8OZ', 2.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S126', 'Bay Leaves', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082508', '8OZ', 6.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S127', 'Cinnamon, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082888', '16OZ', 10.4, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S128', 'Nutmeg, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082896', '16OZ', 13.6, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S129', 'Ginger, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082904', '16OZ', 8.8, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S130', 'Cloves, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082912', '16OZ', 12.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S131', 'Cardamom, Ground', 'Pantry', 'Spices & Seasonings', 'oz', 'Sysco', '4082920', '16OZ', 29.6, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S140', 'Soy Sauce', 'Pantry', 'Condiments', 'oz', 'Sysco', '4082540', '4/1GAL', 76.8, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S141', 'Sunflower Seeds', 'Pantry', 'Nuts & Seeds', 'lb', 'Sysco', '4082674', '25LB', 81.25, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S150', 'Tomatoes, Diced Canned', 'Pantry', 'Canned Goods', 'can', 'Sysco', '4082300', '6/#10', 17.1, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S151', 'Tomato Paste', 'Pantry', 'Canned Goods', 'can', 'Sysco', '4082308', '6/#10', 11.7, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S152', 'Tomatoes, Crushed Canned', 'Pantry', 'Canned Goods', 'can', 'Sysco', '4082316', '6/#10', 18.9, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S160', 'Pasta, Spaghetti', 'Pantry', 'Pasta & Rice', 'lb', 'Sysco', '4082400', '20LB', 25.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S161', 'Pasta, Penne', 'Pantry', 'Pasta & Rice', 'lb', 'Sysco', '4082408', '20LB', 25.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S162', 'Rice, Long Grain', 'Pantry', 'Pasta & Rice', 'lb', 'Sysco', '4082416', '50LB', 42.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S163', 'Rice, Arborio', 'Pantry', 'Pasta & Rice', 'lb', 'Sysco', '4082424', '10LB', 25.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S170', 'Potato, Breakfast Frozen', 'Frozen Foods', 'Frozen Vegetables', 'oz', 'Sysco', '', '6/6LB', 79.92, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S200', 'Tomato, 5x6', 'Produce', 'Vegetables', 'ea', 'Sysco', '', '1/25LB', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S201', 'Potato, Baby Yukon', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/50LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S202', 'Potato, Sweet', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/40LB', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S203', 'Brussels Sprouts', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/25LB', 45.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S204', 'Broccoli, Florets', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '4/3LB', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S205', 'Chili, Fresno', 'Produce', 'Vegetables', 'ea', 'Sysco', '', '1/10LB', 24.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S206', 'Grapes, Red', 'Produce', 'Fruit', 'lb', 'Sysco', '', '1/18LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S207', 'Potato, Baker', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/50LB', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S210', 'Mushrooms, Oyster', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/5LB', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S211', 'Mushrooms, Portobello', 'Produce', 'Vegetables', 'ea', 'Sysco', '', '5LB', 22.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S212', 'Mushrooms, White', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/10LB', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S220', 'Oregano, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '', '1LB', 14.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S221', 'Ginger, Fresh', 'Produce', 'Vegetables', 'lb', 'Sysco', '', '1/5LB', 18.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S222', 'Tarragon, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '', '1LB', 16.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S223', 'Chervil, Fresh', 'Produce', 'Fresh Herbs', 'oz', 'Sysco', '', '1LB', 18.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S230', 'Cheese, Mozzarella', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '', '6/5LB', 89.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S231', 'Gruyere', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '', '1/10LB', 145.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S232', 'Cheese, Monterey Jack', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '', '1/10LB', 52.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S233', 'Cheese, Goat', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '', '2/2LB', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S234', 'Cheese, Mozzarella Balls', 'Dairy & Eggs', 'Cheese', 'oz', 'Sysco', '', '2/3LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S240', 'Chicken, WOG', 'Meat & Seafood', 'Poultry', 'lb', 'Sysco', '', '8/3LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S241', 'Pork, Chops', 'Meat & Seafood', 'Pork', 'oz', 'Sysco', '', '1/10LB', 58.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S242', 'Steak, Flatiron', 'Meat & Seafood', 'Beef', 'oz', 'Sysco', '', '1/10LB', 89.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S243', 'Steak, NY Strip', 'Meat & Seafood', 'Beef', 'oz', 'Sysco', '', '1/10LB', 145.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S250', 'Stock, Fish', 'Stock', 'Fish Stock', 'qt', 'Sysco', '', '12/1QT', 36.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S251', 'Base, Beef', 'Stock', 'Beef Stock', 'oz', 'Sysco', '', '6/1LB', 48.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S252', 'Base, Chicken', 'Stock', 'Chicken Stock', 'oz', 'Sysco', '', '6/1LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S253', 'Base, Vegetable', 'Stock', 'Vegetable Stock', 'oz', 'Sysco', '', '6/1LB', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S260', 'Mustard, Dijon', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '6/12OZ', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S261', 'Mayonnaise', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '4/1GAL', 58.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S262', 'Juice, Lemon', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '12/32OZ', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S263', 'Olives, Kalamata', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '6/2LB', 68.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S264', 'Worcestershire Sauce', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '4/1GAL', 52.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S265', 'Tomato Paste, Tube', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '12/4.5OZ', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S270', 'Oil, Sesame', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '', '12/12OZ', 68.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S271', 'Vinegar, Apple Cider', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '', '4/1GAL', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S272', 'Oil, Extra Virgin Olive', 'Pantry', 'Oils & Vinegars', 'qt', 'Sysco', '', '6/1QT', 89.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S275', 'Wine, White Cooking', 'Pantry', 'Cooking Wines', 'qt', 'Sysco', '', '12/750ML', 72.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S276', 'Wine, Red Cooking', 'Pantry', 'Cooking Wines', 'qt', 'Sysco', '', '12/750ML', 72.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S280', 'Pine Nuts', 'Pantry', 'Nuts & Seeds', 'oz', 'Sysco', '', '1/5LB', 125.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S281', 'Sesame Seeds, White', 'Pantry', 'Nuts & Seeds', 'oz', 'Sysco', '', '6/1LB', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S290', 'Bonito Flakes', 'Pantry', 'Asian', 'oz', 'Sysco', '', '10/3.5OZ', 65.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S291', 'Bread Crumbs, Panko', 'Pantry', 'Breading', 'lb', 'Sysco', '', '6/2.5LB', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S292', 'Cranberries, Dried', 'Pantry', 'Dried Fruits', 'lb', 'Sysco', '', '1/10LB', 52.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S293', 'Juice, Yuzu', 'Pantry', 'Asian', 'oz', 'Sysco', '', '12/5OZ', 85.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S295', 'Baguette', 'Bakery & Bread', 'Bread', 'ea', 'Sysco', '', '24CT', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S296', 'Arborio Rice', 'Pantry', 'Pasta & Rice', 'lb', 'Sysco', '', '1/12LB', 28.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S297', 'Chutney, Major Grey', 'Pantry', 'Condiments', 'oz', 'Sysco', '4758962', '6/26OZ', 42.5, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S298', 'Curry Powder', 'Pantry', 'Spices & Seasonings', 'oz', 'Spiceology', 'SPL-10142', '', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S299', 'Pesto, Basil', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '6/30OZ', 68.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S300', 'Arugula', 'Produce', 'Vegetables', 'oz', 'Sysco', '', '4/5LB', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S301', 'Artichoke Hearts, Marinated', 'Pantry', 'Canned Goods', 'oz', 'Sysco', '', '6/14OZ', 52.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S302', 'Tomatoes, Sun-Dried', 'Pantry', 'Canned Goods', 'oz', 'Sysco', '', '6/7OZ', 38.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S303', 'Cheese, Provolone', 'Dairy & Eggs', 'Cheese', 'lb', 'Sysco', '', '8/1LB', 48.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S304', 'Ham, Black Forest', 'Meat & Seafood', 'Deli Meats', 'lb', 'Sysco', '', '2/6LB', 72.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S305', 'Salami, Genoa', 'Meat & Seafood', 'Deli Meats', 'lb', 'Sysco', '', '2/4LB', 56.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S306', 'Pepperoncini', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '4/1GAL', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S308', 'Ciabatta Roll', 'Bakery & Bread', 'Bread', 'ea', 'Sysco', '', '48CT', 36.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S309', 'Focaccia Bread', 'Bakery & Bread', 'Bread', 'ea', 'Sysco', '', '12CT', 32.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S310', 'Mozzarella, Fresh', 'Dairy & Eggs', 'Cheese', 'oz', 'Sysco', '', '6/1LB', 54.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S311', 'Croissant, Sandwich', 'Bakery & Bread', 'Bread', 'ea', 'Sysco', '', '48CT', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S313', 'Oil, Olive/Canola Blend', 'Pantry', 'Oils & Vinegars', 'oz', 'Sysco', '', '6/1GAL', 95.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S314', 'Balsamic Glaze', 'Pantry', 'Condiments', 'oz', 'Sysco', '', '6/12OZ', 48.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S315', 'Falafel Balls', 'Pantry', 'Prepared', 'oz', 'Sysco', '4774225', '4/4LB', 66.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S316', 'Hummus, Traditional', 'Pantry', 'Condiments', 'oz', 'Sysco', '9669151', '4/3.75LB', 61.95, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S317', 'Tortilla, Garlic Herb 12in', 'Bakery & Bread', 'Bread', 'ea', 'Sysco', '', '12/12CT', 42.0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S318', 'Italian Dressing', 'Pantry', 'Condiments', 'oz', 'Costco', '', '', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S319', 'Turkey Breast, Sliced', 'Meat & Seafood', 'Deli Meats', 'oz', 'Costco', '', '', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S320', 'Cheese, Feta Crumbled', 'Dairy & Eggs', 'Cheese', 'oz', 'Costco', '', '', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('S321', 'Croutons, Seasoned', 'Pantry', 'Bread', 'oz', 'Restaurant Depot', '', '', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SYS-2644625', 'Cranberry Juice Cocktail, Simply', 'Beverages', 'Juice', 'ea', 'Sysco', '2644625', '12/11.5OZ', 30.75, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], '', true, false),
('SH001', 'Sausage, Turkey Link Fully Cooked', 'Protein', 'Breakfast Meats', 'lb', 'Rose Packing', '3431631', '1/10/LB', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH002', 'Butter, Salted Foil Wrapped 47ct GF', 'Dairy & Eggs', 'Butter', 'lb', 'Shamrock Farms', '1959341', '4/4.25/LB', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'REFRIGERATED', true, false),
('SH003', 'Bagel, Plain Sliced 2.3oz', 'Bakery & Bread', 'Bread', 'pk', 'Lender''s', '3232731', '12/6/PK', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH004', 'Oats, Steel Cut', 'Pantry', 'Grains', 'lb', 'Bob''s Red Mill', '3655091', '1/25/LB', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'DRY', true, false),
('SH005', 'Granola, Honey Oat Gluten Free', 'Pantry', 'Grains', 'oz', 'Bob''s Red Mill', '4229191', '4/12/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'DRY', true, false),
('SH006', 'Croissant, Butter 1.2oz Rnd Closed', 'Bakery & Bread', 'Pastries', 'ea', 'Brickfire Bakery', '4626391', '80/1.2/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH007', 'Muffin, Variety 2.125oz', 'Bakery & Bread', 'Pastries', 'ea', 'Brickfire Bakery', '4129561', '96/2.12/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH008', 'Cheese, Cream Cup 1oz Rbst Free', 'Dairy & Eggs', 'Cheese', 'ea', 'Shamrock Farms', '3574441', '100/1/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'REFRIGERATED', true, false),
('SH009', 'Egg, Hard Peeled Premium 144ct', 'Dairy & Eggs', 'Eggs', 'lb', 'Shamrock Chef', '2876131', '1/10/LB', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'REFRIGERATED', true, false),
('SH010', 'Bagel, Plain Sliced Thaw & Serve 2.3oz', 'Bakery & Bread', 'Bread', 'ea', 'Burry', '3269581', '90/2.3/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH011', 'Jelly, Assorted Portion .5oz', 'Pantry', 'Condiments', 'pk', 'Smuckers', '2950711', '1/200/PK', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'DRY', true, false),
('SH012', 'Bread, White Split Top Whole Grain', 'Bakery & Bread', 'Bread', 'oz', 'Alpha Baking', '3243171', '6/24/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH013', 'Danish, Assorted 1.25oz Crown Baked', 'Bakery & Bread', 'Pastries', 'ea', 'Aspire', '1003494', '72/1.25/OZ', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false),
('SH014', 'Egg, Liquid Whole Cage Free', 'Dairy & Eggs', 'Eggs', 'lb', 'Fair Meadow', '4954531', '15/2/LB', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'REFRIGERATED', true, false),
('SH015', 'Bagel, Plain Mini .9oz Sliced', 'Bakery & Bread', 'Bread', 'pk', 'Burry', '2513351', '14/12/PK', 0, '', ARRAY['Baking & Pastry Arts','Culinary Arts','Foodservice'], 'FROZEN', true, false);