// Complete Ingredient List from Excel Order Forms
// Total: 144 items
export const ingredientsList = [
  { id: 'PRO-001', category: 'PRODUCE', name: 'Orange', shamrockCode: '30001', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-002', category: 'PRODUCE', name: 'Lemons', shamrockCode: '30002', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-003', category: 'PRODUCE', name: 'Limes', shamrockCode: '30003', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-004', category: 'PRODUCE', name: 'Red Apples', shamrockCode: '30004', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-005', category: 'PRODUCE', name: 'Green Apples', shamrockCode: '30005', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-006', category: 'PRODUCE', name: 'Strawberry', shamrockCode: '30006', unit: 'pt', unitPrice: 5.00 },
  { id: 'PRO-007', category: 'PRODUCE', name: 'Blueberry', shamrockCode: '30007', unit: 'pt', unitPrice: 5.00 },
  { id: 'PRO-008', category: 'PRODUCE', name: 'Raspberry', shamrockCode: '30008', unit: 'pt', unitPrice: 5.00 },
  { id: 'PRO-009', category: 'PRODUCE', name: 'Blackberry', shamrockCode: '30009', unit: 'pt', unitPrice: 5.00 },
  { id: 'PRO-010', category: 'PRODUCE', name: 'Raspberry Jam', shamrockCode: '30010', unit: 'qt', unitPrice: 5.00 },
  { id: 'BAK-001', category: 'BAKING', name: 'Apricot', shamrockCode: '10001', unit: 'qt', unitPrice: 5.00 },
  { id: 'BAK-002', category: 'BAKING', name: 'Dried Apricots', shamrockCode: '10002', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-003', category: 'BAKING', name: 'Dried Cherries', shamrockCode: '10003', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-004', category: 'BAKING', name: 'Raisin', shamrockCode: '10004', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-011', category: 'PRODUCE', name: 'Lemon Juice', shamrockCode: '30011', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-012', category: 'PRODUCE', name: 'Bananas', shamrockCode: '30012', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-005', category: 'BAKING', name: 'Whole Almonds', shamrockCode: '10005', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-006', category: 'BAKING', name: 'Sliced Almonds', shamrockCode: '10006', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-007', category: 'BAKING', name: 'Pecan Pieces', shamrockCode: '10007', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-008', category: 'BAKING', name: 'Pecan Halves', shamrockCode: '10008', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-009', category: 'BAKING', name: 'Hazelnuts', shamrockCode: '10009', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-010', category: 'BAKING', name: 'Pistachios', shamrockCode: '10010', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-011', category: 'BAKING', name: 'Cashews', shamrockCode: '10011', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-012', category: 'BAKING', name: 'Walnut Pieces', shamrockCode: '10012', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-013', category: 'BAKING', name: 'Walnut Halves', shamrockCode: '10013', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-014', category: 'BAKING', name: 'Shredded Coconut', shamrockCode: '10014', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-015', category: 'BAKING', name: 'Chocolate Chips', shamrockCode: '10015', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-016', category: 'BAKING', name: 'Dk Chocolate Callets', shamrockCode: '10016', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-001', category: 'DAIRY & EGGS', name: 'Milk Chocolate Callets', shamrockCode: '20001', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-017', category: 'BAKING', name: 'Wh. Chocolate Callets', shamrockCode: '10017', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-018', category: 'BAKING', name: 'Cocoa Powder', shamrockCode: '10018', unit: 'oz', unitPrice: 5.00 },
  { id: 'BAK-019', category: 'BAKING', name: 'Dutch Cocoa', shamrockCode: '10019', unit: 'oz', unitPrice: 5.00 },
  { id: 'DAI-002', category: 'DAIRY & EGGS', name: 'Eggs', shamrockCode: '20002', unit: 'Doz', unitPrice: 5.00 },
  { id: 'DAI-003', category: 'DAIRY & EGGS', name: 'Milk', shamrockCode: '20003', unit: 'gallon', unitPrice: 5.00 },
  { id: 'DAI-004', category: 'DAIRY & EGGS', name: 'Heavy Cream', shamrockCode: '20004', unit: 'qt', unitPrice: 5.00 },
  { id: 'DAI-005', category: 'DAIRY & EGGS', name: 'Butter', shamrockCode: '20005', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-006', category: 'DAIRY & EGGS', name: 'Cream Cheese', shamrockCode: '20006', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-007', category: 'DAIRY & EGGS', name: 'Sour Cream', shamrockCode: '20007', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-008', category: 'DAIRY & EGGS', name: 'Yogurt', shamrockCode: '20008', unit: 'ea', unitPrice: 5.00 },
  { id: 'DAI-009', category: 'DAIRY & EGGS', name: 'Buttermilk', shamrockCode: '20009', unit: 'qt', unitPrice: 5.00 },
  { id: 'DAI-010', category: 'DAIRY & EGGS', name: 'Mascarpone', shamrockCode: '20010', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-013', category: 'PRODUCE', name: 'Light Corn Syrup', shamrockCode: '30013', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-014', category: 'PRODUCE', name: 'Dark Corn Syrup', shamrockCode: '30014', unit: 'oz', unitPrice: 5.00 },
  { id: 'PAN-001', category: 'PANTRY', name: 'Honey', shamrockCode: '50001', unit: 'oz', unitPrice: 5.00 },
  { id: 'DAI-011', category: 'DAIRY & EGGS', name: 'Peanut Butter', shamrockCode: '20011', unit: 'oz', unitPrice: 5.00 },
  { id: 'BAK-020', category: 'BAKING', name: 'Vanilla Beans', shamrockCode: '10020', unit: 'ea', unitPrice: 5.00 },
  { id: 'BAK-021', category: 'BAKING', name: 'Gelatin Sheets', shamrockCode: '10021', unit: 'ea', unitPrice: 5.00 },
  { id: 'BAK-022', category: 'BAKING', name: 'Gelatin Granules', shamrockCode: '10022', unit: 'oz', unitPrice: 5.00 },
  { id: 'BAK-023', category: 'BAKING', name: 'Filo Dough', shamrockCode: '10023', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-024', category: 'BAKING', name: 'Puff Pastry', shamrockCode: '10024', unit: 'Sheets', unitPrice: 5.00 },
  { id: 'BAK-025', category: 'BAKING', name: 'AP Flour', shamrockCode: '10025', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-026', category: 'BAKING', name: 'Cake flour', shamrockCode: '10026', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-027', category: 'BAKING', name: 'Bread Flour', shamrockCode: '10027', unit: 'ea', unitPrice: 5.00 },
  { id: 'BAK-028', category: 'BAKING', name: 'Pastry Flour', shamrockCode: '10028', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-029', category: 'BAKING', name: 'White Sugar', shamrockCode: '10029', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-030', category: 'BAKING', name: 'Brown Sugar', shamrockCode: '10030', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-031', category: 'BAKING', name: 'Dk. Brown Sugar', shamrockCode: '10031', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-032', category: 'BAKING', name: 'Powder sugar', shamrockCode: '10032', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-033', category: 'BAKING', name: 'Almond Paste', shamrockCode: '10033', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-015', category: 'PRODUCE', name: 'Ylw Onion', shamrockCode: '30015', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-016', category: 'PRODUCE', name: 'Red Onion', shamrockCode: '30016', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-017', category: 'PRODUCE', name: 'Red Potato', shamrockCode: '30017', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-018', category: 'PRODUCE', name: 'Baker Potato', shamrockCode: '30018', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-019', category: 'PRODUCE', name: 'Garlic Bulb', shamrockCode: '30019', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-020', category: 'PRODUCE', name: 'Shallots', shamrockCode: '30020', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-021', category: 'PRODUCE', name: 'Carrots', shamrockCode: '30021', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-022', category: 'PRODUCE', name: 'Celery', shamrockCode: '30022', unit: 'bnch', unitPrice: 5.00 },
  { id: 'PRO-023', category: 'PRODUCE', name: 'Leeks', shamrockCode: '30023', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-024', category: 'PRODUCE', name: 'Red Bell', shamrockCode: '30024', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-025', category: 'PRODUCE', name: 'Green Bell', shamrockCode: '30025', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-026', category: 'PRODUCE', name: 'Mushrooms', shamrockCode: '30026', unit: '#', unitPrice: 5.00 },
  { id: 'PRO-027', category: 'PRODUCE', name: 'Jalapeno', shamrockCode: '30027', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-028', category: 'PRODUCE', name: 'Cherry Tomato', shamrockCode: '30028', unit: 'pt.', unitPrice: 5.00 },
  { id: 'PRO-029', category: 'PRODUCE', name: 'Avocado', shamrockCode: '30029', unit: 'ea', unitPrice: 5.00 },
  { id: 'PAN-002', category: 'PANTRY', name: 'Aspargus', shamrockCode: '50002', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-030', category: 'PRODUCE', name: 'Corn', shamrockCode: '30030', unit: 'fresh ea', unitPrice: 5.00 },
  { id: 'PRO-031', category: 'PRODUCE', name: 'Romaine', shamrockCode: '30031', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-032', category: 'PRODUCE', name: 'Iceberg', shamrockCode: '30032', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-033', category: 'PRODUCE', name: 'Spinach', shamrockCode: '30033', unit: 'bnch', unitPrice: 5.00 },
  { id: 'PRO-034', category: 'PRODUCE', name: 'spring Mix', shamrockCode: '30034', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-035', category: 'PRODUCE', name: 'Grn onion', shamrockCode: '30035', unit: 'bnch', unitPrice: 5.00 },
  { id: 'PAN-003', category: 'PANTRY', name: 'Roma, tom', shamrockCode: '50003', unit: 'ea', unitPrice: 5.00 },
  { id: 'PAN-004', category: 'PANTRY', name: '5x6 tom', shamrockCode: '50004', unit: 'ea', unitPrice: 5.00 },
  { id: 'PAN-005', category: 'PANTRY', name: 'Cucmbers', shamrockCode: '50005', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-036', category: 'PRODUCE', name: 'Eng Cucumber', shamrockCode: '30036', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-037', category: 'PRODUCE', name: 'Ylw Squash', shamrockCode: '30037', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-038', category: 'PRODUCE', name: 'Zucchini', shamrockCode: '30038', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-039', category: 'PRODUCE', name: 'Oranges', shamrockCode: '30039', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-040', category: 'PRODUCE', name: 'Lemons', shamrockCode: '30040', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-041', category: 'PRODUCE', name: 'Limes', shamrockCode: '30041', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-042', category: 'PRODUCE', name: 'Red Apple', shamrockCode: '30042', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-043', category: 'PRODUCE', name: 'Green Apple', shamrockCode: '30043', unit: 'ea', unitPrice: 5.00 },
  { id: 'PRO-044', category: 'PRODUCE', name: 'Raspberry', shamrockCode: '30044', unit: 'pt', unitPrice: 5.00 },
  { id: 'PAN-006', category: 'PANTRY', name: 'Black Berry', shamrockCode: '50006', unit: 'pt', unitPrice: 5.00 },
  { id: 'PRO-045', category: 'PRODUCE', name: 'Grapes', shamrockCode: '30045', unit: 'lb', unitPrice: 5.00 },
  { id: 'PRO-046', category: 'PRODUCE', name: 'Flat Parsley', shamrockCode: '30046', unit: 'bnch', unitPrice: 5.00 },
  { id: 'PRO-047', category: 'PRODUCE', name: 'Curly Parsley', shamrockCode: '30047', unit: 'Bnch', unitPrice: 5.00 },
  { id: 'PRO-048', category: 'PRODUCE', name: 'Cilantro', shamrockCode: '30048', unit: 'bnch', unitPrice: 5.00 },
  { id: 'PRO-049', category: 'PRODUCE', name: 'Basil', shamrockCode: '30049', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-050', category: 'PRODUCE', name: 'Thyme', shamrockCode: '30050', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-051', category: 'PRODUCE', name: 'Oregano', shamrockCode: '30051', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-052', category: 'PRODUCE', name: 'Dill', shamrockCode: '30052', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-053', category: 'PRODUCE', name: 'Chives', shamrockCode: '30053', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-054', category: 'PRODUCE', name: 'Sage', shamrockCode: '30054', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-055', category: 'PRODUCE', name: 'Ginger Root', shamrockCode: '30055', unit: 'oz', unitPrice: 5.00 },
  { id: 'DAI-012', category: 'DAIRY & EGGS', name: 'Eggs', shamrockCode: '20012', unit: 'Doz', unitPrice: 5.00 },
  { id: 'DAI-013', category: 'DAIRY & EGGS', name: 'Milk', shamrockCode: '20013', unit: 'qt', unitPrice: 5.00 },
  { id: 'DAI-014', category: 'DAIRY & EGGS', name: 'Heavy Cream', shamrockCode: '20014', unit: 'qt', unitPrice: 5.00 },
  { id: 'DAI-015', category: 'DAIRY & EGGS', name: 'Butter', shamrockCode: '20015', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-016', category: 'DAIRY & EGGS', name: 'Cream Cheese', shamrockCode: '20016', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-017', category: 'DAIRY & EGGS', name: 'Sour Cream', shamrockCode: '20017', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-018', category: 'DAIRY & EGGS', name: 'Yogurt', shamrockCode: '20018', unit: 'ea', unitPrice: 5.00 },
  { id: 'DAI-019', category: 'DAIRY & EGGS', name: 'Cheddar', shamrockCode: '20019', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-020', category: 'DAIRY & EGGS', name: 'Mozzarella', shamrockCode: '20020', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-021', category: 'DAIRY & EGGS', name: 'Gruyere', shamrockCode: '20021', unit: 'lb', unitPrice: 5.00 },
  { id: 'PAN-007', category: 'PANTRY', name: 'Parmasean', shamrockCode: '50007', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-022', category: 'DAIRY & EGGS', name: 'Monterey Jack', shamrockCode: '20022', unit: 'lb', unitPrice: 5.00 },
  { id: 'DAI-023', category: 'DAIRY & EGGS', name: 'Goat cheese', shamrockCode: '20023', unit: 'lb', unitPrice: 5.00 },
  { id: 'PROT-001', category: 'PROTEINS', name: 'Bacon', shamrockCode: '40001', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-034', category: 'BAKING', name: 'Baguette', shamrockCode: '10034', unit: 'ea', unitPrice: 5.00 },
  { id: 'PAN-008', category: 'PANTRY', name: 'Honey', shamrockCode: '50008', unit: 'oz', unitPrice: 5.00 },
  { id: 'PAN-009', category: 'PANTRY', name: 'Dijon mustard', shamrockCode: '50009', unit: 'oz', unitPrice: 5.00 },
  { id: 'PAN-010', category: 'PANTRY', name: 'Mayo', shamrockCode: '50010', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-056', category: 'PRODUCE', name: 'Lemon juice', shamrockCode: '30056', unit: 'oz', unitPrice: 5.00 },
  { id: 'PRO-057', category: 'PRODUCE', name: 'Tomato paste', shamrockCode: '30057', unit: 'oz', unitPrice: 5.00 },
  { id: 'PAN-011', category: 'PANTRY', name: 'Kalamatas', shamrockCode: '50011', unit: 'oz', unitPrice: 5.00 },
  { id: 'PROT-002', category: 'PROTEINS', name: 'Beef/Chix/Veg Base', shamrockCode: '40002', unit: 'ea', unitPrice: 5.00 },
  { id: 'PROT-003', category: 'PROTEINS', name: 'Beef stock', shamrockCode: '40003', unit: 'qt', unitPrice: 5.00 },
  { id: 'PROT-004', category: 'PROTEINS', name: 'chicken stock', shamrockCode: '40004', unit: 'qt', unitPrice: 5.00 },
  { id: 'PROT-005', category: 'PROTEINS', name: 'Fish stock', shamrockCode: '40005', unit: 'qt', unitPrice: 5.00 },
  { id: 'BAK-035', category: 'BAKING', name: 'AP Flour', shamrockCode: '10035', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-036', category: 'BAKING', name: 'Cake flour', shamrockCode: '10036', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-037', category: 'BAKING', name: 'Bread Flour', shamrockCode: '10037', unit: 'ea', unitPrice: 5.00 },
  { id: 'BAK-038', category: 'BAKING', name: 'White Sugar', shamrockCode: '10038', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-039', category: 'BAKING', name: 'Brown Sugar', shamrockCode: '10039', unit: 'lb', unitPrice: 5.00 },
  { id: 'BAK-040', category: 'BAKING', name: 'Powder sugar', shamrockCode: '10040', unit: 'lb', unitPrice: 5.00 },
  { id: 'PAN-012', category: 'PANTRY', name: 'EVO', shamrockCode: '50012', unit: 'qt', unitPrice: 5.00 },
  { id: 'PAN-013', category: 'PANTRY', name: 'Canola Oil', shamrockCode: '50013', unit: 'qt', unitPrice: 5.00 },
  { id: 'PAN-014', category: 'PANTRY', name: 'Balsamic vin', shamrockCode: '50014', unit: 'qt', unitPrice: 5.00 },
  { id: 'PAN-015', category: 'PANTRY', name: 'White wine', shamrockCode: '50015', unit: 'vin. Qt', unitPrice: 5.00 },
  { id: 'PAN-016', category: 'PANTRY', name: 'Red wine Vin. Qt', shamrockCode: '50016', unit: 'ea', unitPrice: 5.00 },
  { id: 'PAN-017', category: 'PANTRY', name: 'Worcestershire', shamrockCode: '50017', unit: 'qt', unitPrice: 5.00 },
  { id: 'PAN-018', category: 'PANTRY', name: 'Soy Sauce', shamrockCode: '50018', unit: 'qt', unitPrice: 5.00 },
  { id: 'PRO-058', category: 'PRODUCE', name: 'Apple Cider Vin', shamrockCode: '30058', unit: 'qt', unitPrice: 5.00 },
];

export const categories = [...new Set(ingredientsList.map(item => item.category))];
